name: release

on:
  push:
    branches: [deploy]
    tags: [v*]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        # install deps required for building sdist/wheels
        python -m pip install --upgrade pip
        pip install -r requirements/dist.txt
        pip install -r requirements/test.txt

    - name: Test with pytest
      # forcibly enable pytest colors
      env:
        PY_COLORS: 1
      run: python setup.py test

    - name: Build sdist
      run: |
        git clean -fxd
        # use release version of pyproject.toml
        cp requirements/pyproject.toml ./pyproject.toml
        # build sdist
        python setup.py sdist

    - name: Build wheels
      uses: joerick/cibuildwheel@v1.10.0
      with:
        output-dir: dist
      env:
        CIBW_BUILD: cp38-* cp39-*
        CIBW_ARCHS_LINUX: x86_64 i686
        CIBW_MANYLINUX_X86_64_IMAGE: manylinux2014
        CIBW_MANYLINUX_I686_IMAGE: manylinux2014
        CIBW_BEFORE_BUILD: pip install -r {project}/requirements/dist.txt
        CIBW_BEFORE_TEST: pip install -r {project}/requirements/test.txt
        CIBW_TEST_COMMAND: py.test {project}/tests

    - name: Output dist file info
      run: |
        ls dist/
        tar -ztf dist/*.tar.gz | sort
        sha512sum dist/*

    - name: Upload files for tagged releases
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      # only upload files for tagged releases
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        pip install twine
        twine upload dist/*
