name: release

on:
  push:
    branches: [deploy]
    tags: [v*]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        # pull in pkgdist dep lists
        git clone https://github.com/pkgcore/pkgdist.git
        cp -Rv pkgdist/requirements/* requirements/

    - name: Build dist files
      env:
        CIBW_BUILD: "cp38-* cp39-*"
        CIBW_BEFORE_BUILD: "pip install -r {project}/requirements/wheel.txt"
        CIBW_BEFORE_TEST: "pip install -r {project}/requirements/test.txt"
        CIBW_TEST_COMMAND: "py.test {project}/tests"
      run: pkgdist/build-dist-files.sh

    - name: Upload files for tagged releases
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
      # only upload files for tagged releases
      if: startsWith(github.ref, 'refs/tags/')
      run: twine upload dist/*
